services:
  server_instance:
    container_name: server_instance
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - docx-network

  nginx:
    build:
      dockerfile: nginx/nginx.dockerfile
      context: .
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "4040:80"
    networks:
      - docx-network
    depends_on:
      - "server_instance"

volumes:
  postgres_data:

networks:
  docx-network:
    name: docx-network
    driver: bridge