name: Deploy to GCLOUD

on:
  push:
    branches:
      - main

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurando SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY_PUB }}" >> ~/.ssh/known_hosts
          ssh-keyscan -H "${{ secrets.VM_IP }}" >> ~/.ssh/known_hosts

      - name: Checando Tipagem
        run: |
          ssh -t -i ~/.ssh/id_rsa "${{ secrets.SSH_CON }}" << 'EOF'
            cd ..
            cd shared
            cd docx-backend
            ls
          EOF
        continue-on-error: false

      - name: Fazendo deploy
        run: |
          ssh -t -i ~/.ssh/id_rsa "${{ secrets.SSH_CON }}" << 'EOF'
            cd ..
            cd shared
            cd docx-backend
            bash deploy.sh
          EOF