name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          passphrase: ${{secrets.SSH_PASS }}
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            sudo -i
            cd /home/paulo_ribeiro/docx-backend
            git pull origin main && npm run deploy